#pragma once
#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.Foundation.Collections.h>
#include <winrt/Windows.ApplicationModel.h>
#include <winrt/Windows.Storage.h>
#include <windows.h>
#include <filesystem>
#include <string_view>
#include <string>
#include <iostream>
#include "../shared/JuliaVersionDatabase.h"
