#pragma once
#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.Foundation.Collections.h>
#include <winrt/Windows.ApplicationModel.h>
#include <winrt/Windows.Storage.h>
#include <windows.h>
#include <filesystem>
#include <string_view>
#include <string>
#include <codecvt>
#include <iostream>
#include <fstream>
#include "JuliaVersionDatabase.h"
#include "version.h"
#include "../json/single_include/nlohmann/json.hpp"
