name: Clippy

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  issues: write
  pull-requests: write

jobs:
  clippy:
    name: Clippy Check (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            features: selfupdate,binjuliainstaller,binjulialauncher
          - os: windows-latest
            features: windowsstore,windowsappinstaller,binjuliainstaller,binjulialauncher
          - os: macos-latest
            features: selfupdate,binjuliainstaller,binjulialauncher
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
        with:
          components: clippy
      - name: Run clippy
        run: cargo clippy --workspace --features ${{ matrix.features }} -- -D warnings
