name: rustfmt

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

# https://github.com/reviewdog/action-suggester?tab=readme-ov-file#required-permissions
permissions:
  contents: read
  checks: write
  issues: write
  pull-requests: write

jobs:
  rustfmt:
    name: Rustfmt Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
        with:
          components: rustfmt
      - name: Rustfmt check
        if: ${{ github.event_name != 'pull_request' }}
        run: cargo fmt -- --check -v
      - name: Rustfmt PR
        if: ${{ github.event_name == 'pull_request' }}
        run: cargo fmt -- --check -v
      - name: Suggest format changes
        if: ${{ github.event_name == 'pull_request' && failure() }}
        uses: reviewdog/action-suggester@2558ba17e65a9039e73764a73009fc05fef28a46 # v1.24.3
        with:
          tool_name: rustfmt
          fail_level: error
